- name: 'Theme style'
  uriPattern: '{node}theme.css'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'themestyle'
  httpMethods: ['GET']
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true

- name: 'Favicon: icon.svg'
  uriPattern: '{node}icon.svg'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'favicon-svg'
  httpMethods: ['GET']
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true

- name: 'Favicon: apple-touch-icon.png'
  uriPattern: '{node}apple-touch-icon.png'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'favicon-png'
  httpMethods: ['GET']
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true

- name: 'Favicon: favicon-96x96.png'
  uriPattern: '{node}favicon-96x96.png'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'favicon-96-png'
  httpMethods: ['GET']
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true

- name: 'Favicon: favicon.ico'
  uriPattern: '{node}favicon.ico'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'favicon-ico'
  httpMethods: ['GET']
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true
