Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          theme:
            shadow:
              type: string
              search:
                indexing: false
              ui:
                reloadPageIfChanged: true
                inspector:
                  group: themeShadows
                  editor: Neos.Neos/Inspector/Editors/SelectBoxEditor
                  editorOptions:
                    minimumResultsForSearch: -1
                    dataSourceIdentifier: litefyr-style-shadow
                    dataSourceAdditionalData:
                      disabled: []
            color:
              blackOrWhite:
                type: string
                search:
                  indexing: false
                ui:
                  reloadPageIfChanged: true
                  inspector:
                    editor: Neos.Neos/Inspector/Editors/SelectBoxEditor
                    editorOptions:
                      values:
                        black:
                          label: Black
                        white:
                          label: White
              required:
                type: string
                search:
                  indexing: false
                ui:
                  reloadPageIfChanged: true
                  inspector:
                    editor: 'Carbon.ColorPicker/OKLCH'
                    editorOptions:
                      allowEmpty: false
                validation:
                  Neos.Neos/Validation/NotEmptyValidator: {}
              optional:
                type: string
                search:
                  indexing: false
                ui:
                  reloadPageIfChanged: true
                  inspector:
                    editor: 'Carbon.ColorPicker/OKLCH'
                    editorOptions:
                      allowEmpty: true
