Litefyr:
  Integration:
    flowCommandsOnStartup:
      StyleCSS: style:css
      StyleCodePen: style:codepen
  Style:
    codepenProperties:
      # Add here you cli command to execute after a codepen property is published to live
      # example:
      # cliCommandAfterPublishToLive:
      #   - 'node Build/Carbon.Pipeline/postcss.mjs --production --silent'
      #   - 'php flow cache:clearincludeassets'
      cliCommandAfterPublishToLive: null
    additionalThemeSelector: {}
    default:
      scheme: zinc
      mainColor: '#65a30d'
      rounded: 0
    shadows:
      # https://tailwindcss.com/docs/box-shadow
      # Colored shadows are not supported like this
      # Corresponding CSS File: Litefyr.Presentation/Resources/Private/Assets/Global/Shadows.pcss
      none: '0 0 #0000'
      px: '0 0px 0px 1px rgb(0 0 0 / 0.5)'
      sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)'
      default: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)'
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)'
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)'
      xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)'
      2xl: '0 25px 50px -12px rgb(0 0 0 / 0.25)'
