Neos:
  Flow:
    mvc:
      routes:
        'Litefyr.Style':
          position: 'start'
  Neos:
    fusion:
      autoInclude:
        Litefyr.Style: true
    userInterface:
      translation:
        autoInclude:
          Litefyr.Style:
            - 'NodeTypes/*'
    Ui:
      resources:
        javascript:
          Litefyr.Style:
            resource: resource://Litefyr.Style/Public/Editors/Plugin.js
            attributes:
              type: 'module'
        stylesheets:
          Litefyr.Style:
            resource: resource://Litefyr.Style/Public/Editors/Plugin.css
      frontendConfiguration:
        'Litefyr.Style.FontEditor':
          allowEmpty: true
          disabled: false
          roundedButton: 0
          colorContrastThreshold: 65
          colors: []
          useCarbonWebfonts: true
          fonts: {}
