Neos:
  Flow:
    mvc:
      routes:
        'Litefyr.Style':
          position: 'start'
  Neos:
    fusion:
      autoInclude:
        Litefyr.Style: true
    userInterface:
      translation:
        autoInclude:
          Litefyr.Style:
            - 'NodeTypes/*'
    Ui:
      resources:
        javascript:
          Litefyr.Style:
            resource: resource://Litefyr.Style/Public/Editors/Plugin.js
        stylesheets:
          Litefyr.Style:
            resource: resource://Litefyr.Style/Public/Editors/Plugin.css
      frontendConfiguration:
        LitefyrStyleEditorsFont:
          folder: '/_Resources/Static/Packages/Litefyr.Style/Fonts'
          fallbackFont: Inter
          fallback:
            Display: "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"
            Handwriting: "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"
            Sans Serif: "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"
            Serif: "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif"
            Monospace: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
          # If fontWeight is an array, it has multiple fonts, if it is a number it is a fixed font weight (e.g. 400)
          # if it is a string, it is a range of font weights (e.g. "100 900")
          # If you want a specific font location, you can use the filepath property
          fonts:
            # ExampleCustom
            # MyFancyFont:
            #   group: Display
            #   fontWeight: 400
            #   filepath: "/_Resources/Static/Packages/Litefyr.Distribution/Fonts/MyFancyFont.ttf"
            Anybody-Italic:
              group: Display
              fontWeight: '100 900'
            Anybody:
              group: Display
              fontWeight: '100 900'
            Brusher:
              group: Handwriting
              fontWeight: 700
            Cabin:
              group: Sans Serif
              fontWeight: '400 700'
            Cabin-Italic:
              group: Sans Serif
              fontWeight: '400 700'
            Cabin-Sketch:
              group: Display
              fontWeight:
                - 400
                - 700
            Caveat:
              group: Handwriting
              fontWeight: '400 700'
            Cinzel:
              group: Serif
              fontWeight: '400 900'
            CrimsonPro:
              group: Serif
              fontWeight: '200 900'
            CrimsonPro-Italic:
              group: Serif
              fontWeight: '200 900'
            DancingScript:
              group: Handwriting
              fontWeight: '400 700'
            DynaPuff:
              group: Display
              fontWeight: '400 700'
            EduQLDBeginner:
              group: Handwriting
              fontWeight: '400 700'
            ElMessiri:
              group: Sans Serif
              fontWeight: '400 700'
            ExpletusSans:
              group: Display
              fontWeight: '400 700'
            ExpletusSans-Italic:
              group: Display
              fontWeight: '400 700'
            Grandstander:
              group: Display
              fontWeight: '100 900'
            Grandstander-Italic:
              group: Display
              fontWeight: '100 900'
            Inter:
              group: Sans Serif
              fontWeight: '100 900'
            InterTight:
              group: Sans Serif
              fontWeight: '100 900'
            InterTight-Italic:
              group: Sans Serif
              fontWeight: '100 900'
            Jura:
              group: Sans Serif
              fontWeight: '300 700'
            Lemonada:
              group: Display
              fontWeight: '300 700'
            Lexend:
              group: Sans Serif
              fontWeight: '100 900'
            MavenPro:
              group: Sans Serif
              fontWeight: '400 900'
            Merienda:
              group: Handwriting
              fontWeight: '300 900'
            Montserrat:
              group: Sans Serif
              fontWeight: '100 900'
            Montserrat-Italic:
              group: Sans Serif
              fontWeight: '100 900'
            NotoSansDisplay:
              group: Sans Serif
              fontWeight: '100 900'
            NotoSansDisplay-Italic:
              group: Sans Serif
              fontWeight: '100 900'
            NotoSansMono:
              group: Monospace
              fontWeight: '100 900'
            OpenSans:
              group: Sans Serif
              fontWeight: '300 800'
            OpenSans-Italic:
              group: Sans Serif
              fontWeight: '300 800'
            PlayfairDisplay:
              group: Serif
              fontWeight: '400 900'
            PlayfairDisplay-Italic:
              group: Serif
              fontWeight: '400 900'
            PublicSans:
              group: Sans Serif
              fontWeight: '100 900'
            PublicSans-Italic:
              group: Sans Serif
              fontWeight: '100 900'
            Raleway:
              group: Sans Serif
              fontWeight: '100 900'
            Raleway-Italic:
              group: Sans Serif
              fontWeight: '100 900'
            ReadexPro:
              group: Sans Serif
              fontWeight: '160 700'
            RobotoSerif:
              group: Serif
              fontWeight: '100 900'
            RobotoSerif-Italic:
              group: Serif
              fontWeight: '100 900'
            RobotoSlab:
              group: Serif
              fontWeight: '100 900'
            Smooch:
              group: Sans Serif
              fontWeight: '100 900'
            Vollkorn:
              group: Serif
              fontWeight: '400 900'
            Vollkorn-Italic:
              group: Serif
              fontWeight: '400 900'
            WorkSans:
              group: Sans Serif
              fontWeight: '100 900'
            WorkSans-Italic:
              group: Sans Serif
              fontWeight: '100 900'
            Yrsa:
              group: Serif
              fontWeight: '300 700'
            Yrsa-Italic:
              group: Serif
              fontWeight: '300 700'
